
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Hero` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Hero
 * 
 */
export type HeroModel = runtime.Types.Result.DefaultSelection<Prisma.$HeroPayload>

export type AggregateHero = {
  _count: HeroCountAggregateOutputType | null
  _min: HeroMinAggregateOutputType | null
  _max: HeroMaxAggregateOutputType | null
}

export type HeroMinAggregateOutputType = {
  id: string | null
  name: string | null
  headline: string | null
  subheadline: string | null
  description: string | null
  profileImage: string | null
  resumeUrl: string | null
  githubUrl: string | null
  linkedinUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type HeroMaxAggregateOutputType = {
  id: string | null
  name: string | null
  headline: string | null
  subheadline: string | null
  description: string | null
  profileImage: string | null
  resumeUrl: string | null
  githubUrl: string | null
  linkedinUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type HeroCountAggregateOutputType = {
  id: number
  name: number
  headline: number
  subheadline: number
  description: number
  profileImage: number
  resumeUrl: number
  githubUrl: number
  linkedinUrl: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type HeroMinAggregateInputType = {
  id?: true
  name?: true
  headline?: true
  subheadline?: true
  description?: true
  profileImage?: true
  resumeUrl?: true
  githubUrl?: true
  linkedinUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type HeroMaxAggregateInputType = {
  id?: true
  name?: true
  headline?: true
  subheadline?: true
  description?: true
  profileImage?: true
  resumeUrl?: true
  githubUrl?: true
  linkedinUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type HeroCountAggregateInputType = {
  id?: true
  name?: true
  headline?: true
  subheadline?: true
  description?: true
  profileImage?: true
  resumeUrl?: true
  githubUrl?: true
  linkedinUrl?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type HeroAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Hero to aggregate.
   */
  where?: Prisma.HeroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Heroes to fetch.
   */
  orderBy?: Prisma.HeroOrderByWithRelationInput | Prisma.HeroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HeroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Heroes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Heroes
  **/
  _count?: true | HeroCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HeroMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HeroMaxAggregateInputType
}

export type GetHeroAggregateType<T extends HeroAggregateArgs> = {
      [P in keyof T & keyof AggregateHero]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHero[P]>
    : Prisma.GetScalarType<T[P], AggregateHero[P]>
}




export type HeroGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HeroWhereInput
  orderBy?: Prisma.HeroOrderByWithAggregationInput | Prisma.HeroOrderByWithAggregationInput[]
  by: Prisma.HeroScalarFieldEnum[] | Prisma.HeroScalarFieldEnum
  having?: Prisma.HeroScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HeroCountAggregateInputType | true
  _min?: HeroMinAggregateInputType
  _max?: HeroMaxAggregateInputType
}

export type HeroGroupByOutputType = {
  id: string
  name: string
  headline: string
  subheadline: string | null
  description: string
  profileImage: string | null
  resumeUrl: string | null
  githubUrl: string | null
  linkedinUrl: string | null
  createdAt: Date
  updatedAt: Date
  _count: HeroCountAggregateOutputType | null
  _min: HeroMinAggregateOutputType | null
  _max: HeroMaxAggregateOutputType | null
}

type GetHeroGroupByPayload<T extends HeroGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HeroGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HeroGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HeroGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HeroGroupByOutputType[P]>
      }
    >
  >



export type HeroWhereInput = {
  AND?: Prisma.HeroWhereInput | Prisma.HeroWhereInput[]
  OR?: Prisma.HeroWhereInput[]
  NOT?: Prisma.HeroWhereInput | Prisma.HeroWhereInput[]
  id?: Prisma.StringFilter<"Hero"> | string
  name?: Prisma.StringFilter<"Hero"> | string
  headline?: Prisma.StringFilter<"Hero"> | string
  subheadline?: Prisma.StringNullableFilter<"Hero"> | string | null
  description?: Prisma.StringFilter<"Hero"> | string
  profileImage?: Prisma.StringNullableFilter<"Hero"> | string | null
  resumeUrl?: Prisma.StringNullableFilter<"Hero"> | string | null
  githubUrl?: Prisma.StringNullableFilter<"Hero"> | string | null
  linkedinUrl?: Prisma.StringNullableFilter<"Hero"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Hero"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Hero"> | Date | string
}

export type HeroOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  headline?: Prisma.SortOrder
  subheadline?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  profileImage?: Prisma.SortOrderInput | Prisma.SortOrder
  resumeUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  githubUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedinUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HeroWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.HeroWhereInput | Prisma.HeroWhereInput[]
  OR?: Prisma.HeroWhereInput[]
  NOT?: Prisma.HeroWhereInput | Prisma.HeroWhereInput[]
  name?: Prisma.StringFilter<"Hero"> | string
  headline?: Prisma.StringFilter<"Hero"> | string
  subheadline?: Prisma.StringNullableFilter<"Hero"> | string | null
  description?: Prisma.StringFilter<"Hero"> | string
  profileImage?: Prisma.StringNullableFilter<"Hero"> | string | null
  resumeUrl?: Prisma.StringNullableFilter<"Hero"> | string | null
  githubUrl?: Prisma.StringNullableFilter<"Hero"> | string | null
  linkedinUrl?: Prisma.StringNullableFilter<"Hero"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Hero"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Hero"> | Date | string
}, "id">

export type HeroOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  headline?: Prisma.SortOrder
  subheadline?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrder
  profileImage?: Prisma.SortOrderInput | Prisma.SortOrder
  resumeUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  githubUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  linkedinUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.HeroCountOrderByAggregateInput
  _max?: Prisma.HeroMaxOrderByAggregateInput
  _min?: Prisma.HeroMinOrderByAggregateInput
}

export type HeroScalarWhereWithAggregatesInput = {
  AND?: Prisma.HeroScalarWhereWithAggregatesInput | Prisma.HeroScalarWhereWithAggregatesInput[]
  OR?: Prisma.HeroScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HeroScalarWhereWithAggregatesInput | Prisma.HeroScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Hero"> | string
  name?: Prisma.StringWithAggregatesFilter<"Hero"> | string
  headline?: Prisma.StringWithAggregatesFilter<"Hero"> | string
  subheadline?: Prisma.StringNullableWithAggregatesFilter<"Hero"> | string | null
  description?: Prisma.StringWithAggregatesFilter<"Hero"> | string
  profileImage?: Prisma.StringNullableWithAggregatesFilter<"Hero"> | string | null
  resumeUrl?: Prisma.StringNullableWithAggregatesFilter<"Hero"> | string | null
  githubUrl?: Prisma.StringNullableWithAggregatesFilter<"Hero"> | string | null
  linkedinUrl?: Prisma.StringNullableWithAggregatesFilter<"Hero"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Hero"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Hero"> | Date | string
}

export type HeroCreateInput = {
  id?: string
  name: string
  headline: string
  subheadline?: string | null
  description: string
  profileImage?: string | null
  resumeUrl?: string | null
  githubUrl?: string | null
  linkedinUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HeroUncheckedCreateInput = {
  id?: string
  name: string
  headline: string
  subheadline?: string | null
  description: string
  profileImage?: string | null
  resumeUrl?: string | null
  githubUrl?: string | null
  linkedinUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HeroUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  headline?: Prisma.StringFieldUpdateOperationsInput | string
  subheadline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  githubUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HeroUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  headline?: Prisma.StringFieldUpdateOperationsInput | string
  subheadline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  githubUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HeroCreateManyInput = {
  id?: string
  name: string
  headline: string
  subheadline?: string | null
  description: string
  profileImage?: string | null
  resumeUrl?: string | null
  githubUrl?: string | null
  linkedinUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HeroUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  headline?: Prisma.StringFieldUpdateOperationsInput | string
  subheadline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  githubUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HeroUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  headline?: Prisma.StringFieldUpdateOperationsInput | string
  subheadline?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.StringFieldUpdateOperationsInput | string
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resumeUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  githubUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  linkedinUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HeroCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  headline?: Prisma.SortOrder
  subheadline?: Prisma.SortOrder
  description?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  resumeUrl?: Prisma.SortOrder
  githubUrl?: Prisma.SortOrder
  linkedinUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HeroMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  headline?: Prisma.SortOrder
  subheadline?: Prisma.SortOrder
  description?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  resumeUrl?: Prisma.SortOrder
  githubUrl?: Prisma.SortOrder
  linkedinUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HeroMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  headline?: Prisma.SortOrder
  subheadline?: Prisma.SortOrder
  description?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  resumeUrl?: Prisma.SortOrder
  githubUrl?: Prisma.SortOrder
  linkedinUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type HeroSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  headline?: boolean
  subheadline?: boolean
  description?: boolean
  profileImage?: boolean
  resumeUrl?: boolean
  githubUrl?: boolean
  linkedinUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["hero"]>

export type HeroSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  headline?: boolean
  subheadline?: boolean
  description?: boolean
  profileImage?: boolean
  resumeUrl?: boolean
  githubUrl?: boolean
  linkedinUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["hero"]>

export type HeroSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  headline?: boolean
  subheadline?: boolean
  description?: boolean
  profileImage?: boolean
  resumeUrl?: boolean
  githubUrl?: boolean
  linkedinUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["hero"]>

export type HeroSelectScalar = {
  id?: boolean
  name?: boolean
  headline?: boolean
  subheadline?: boolean
  description?: boolean
  profileImage?: boolean
  resumeUrl?: boolean
  githubUrl?: boolean
  linkedinUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type HeroOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "headline" | "subheadline" | "description" | "profileImage" | "resumeUrl" | "githubUrl" | "linkedinUrl" | "createdAt" | "updatedAt", ExtArgs["result"]["hero"]>

export type $HeroPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Hero"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    headline: string
    subheadline: string | null
    description: string
    profileImage: string | null
    resumeUrl: string | null
    githubUrl: string | null
    linkedinUrl: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["hero"]>
  composites: {}
}

export type HeroGetPayload<S extends boolean | null | undefined | HeroDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HeroPayload, S>

export type HeroCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HeroFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HeroCountAggregateInputType | true
  }

export interface HeroDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Hero'], meta: { name: 'Hero' } }
  /**
   * Find zero or one Hero that matches the filter.
   * @param {HeroFindUniqueArgs} args - Arguments to find a Hero
   * @example
   * // Get one Hero
   * const hero = await prisma.hero.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HeroFindUniqueArgs>(args: Prisma.SelectSubset<T, HeroFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HeroClient<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Hero that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HeroFindUniqueOrThrowArgs} args - Arguments to find a Hero
   * @example
   * // Get one Hero
   * const hero = await prisma.hero.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HeroFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HeroFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HeroClient<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hero that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeroFindFirstArgs} args - Arguments to find a Hero
   * @example
   * // Get one Hero
   * const hero = await prisma.hero.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HeroFindFirstArgs>(args?: Prisma.SelectSubset<T, HeroFindFirstArgs<ExtArgs>>): Prisma.Prisma__HeroClient<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hero that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeroFindFirstOrThrowArgs} args - Arguments to find a Hero
   * @example
   * // Get one Hero
   * const hero = await prisma.hero.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HeroFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HeroFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HeroClient<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Heroes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeroFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Heroes
   * const heroes = await prisma.hero.findMany()
   * 
   * // Get first 10 Heroes
   * const heroes = await prisma.hero.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const heroWithIdOnly = await prisma.hero.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HeroFindManyArgs>(args?: Prisma.SelectSubset<T, HeroFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Hero.
   * @param {HeroCreateArgs} args - Arguments to create a Hero.
   * @example
   * // Create one Hero
   * const Hero = await prisma.hero.create({
   *   data: {
   *     // ... data to create a Hero
   *   }
   * })
   * 
   */
  create<T extends HeroCreateArgs>(args: Prisma.SelectSubset<T, HeroCreateArgs<ExtArgs>>): Prisma.Prisma__HeroClient<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Heroes.
   * @param {HeroCreateManyArgs} args - Arguments to create many Heroes.
   * @example
   * // Create many Heroes
   * const hero = await prisma.hero.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HeroCreateManyArgs>(args?: Prisma.SelectSubset<T, HeroCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Heroes and returns the data saved in the database.
   * @param {HeroCreateManyAndReturnArgs} args - Arguments to create many Heroes.
   * @example
   * // Create many Heroes
   * const hero = await prisma.hero.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Heroes and only return the `id`
   * const heroWithIdOnly = await prisma.hero.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HeroCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HeroCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Hero.
   * @param {HeroDeleteArgs} args - Arguments to delete one Hero.
   * @example
   * // Delete one Hero
   * const Hero = await prisma.hero.delete({
   *   where: {
   *     // ... filter to delete one Hero
   *   }
   * })
   * 
   */
  delete<T extends HeroDeleteArgs>(args: Prisma.SelectSubset<T, HeroDeleteArgs<ExtArgs>>): Prisma.Prisma__HeroClient<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Hero.
   * @param {HeroUpdateArgs} args - Arguments to update one Hero.
   * @example
   * // Update one Hero
   * const hero = await prisma.hero.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HeroUpdateArgs>(args: Prisma.SelectSubset<T, HeroUpdateArgs<ExtArgs>>): Prisma.Prisma__HeroClient<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Heroes.
   * @param {HeroDeleteManyArgs} args - Arguments to filter Heroes to delete.
   * @example
   * // Delete a few Heroes
   * const { count } = await prisma.hero.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HeroDeleteManyArgs>(args?: Prisma.SelectSubset<T, HeroDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Heroes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeroUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Heroes
   * const hero = await prisma.hero.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HeroUpdateManyArgs>(args: Prisma.SelectSubset<T, HeroUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Heroes and returns the data updated in the database.
   * @param {HeroUpdateManyAndReturnArgs} args - Arguments to update many Heroes.
   * @example
   * // Update many Heroes
   * const hero = await prisma.hero.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Heroes and only return the `id`
   * const heroWithIdOnly = await prisma.hero.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HeroUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HeroUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Hero.
   * @param {HeroUpsertArgs} args - Arguments to update or create a Hero.
   * @example
   * // Update or create a Hero
   * const hero = await prisma.hero.upsert({
   *   create: {
   *     // ... data to create a Hero
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Hero we want to update
   *   }
   * })
   */
  upsert<T extends HeroUpsertArgs>(args: Prisma.SelectSubset<T, HeroUpsertArgs<ExtArgs>>): Prisma.Prisma__HeroClient<runtime.Types.Result.GetResult<Prisma.$HeroPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Heroes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeroCountArgs} args - Arguments to filter Heroes to count.
   * @example
   * // Count the number of Heroes
   * const count = await prisma.hero.count({
   *   where: {
   *     // ... the filter for the Heroes we want to count
   *   }
   * })
  **/
  count<T extends HeroCountArgs>(
    args?: Prisma.Subset<T, HeroCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HeroCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Hero.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeroAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HeroAggregateArgs>(args: Prisma.Subset<T, HeroAggregateArgs>): Prisma.PrismaPromise<GetHeroAggregateType<T>>

  /**
   * Group by Hero.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeroGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HeroGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HeroGroupByArgs['orderBy'] }
      : { orderBy?: HeroGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HeroGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHeroGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Hero model
 */
readonly fields: HeroFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Hero.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HeroClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Hero model
 */
export interface HeroFieldRefs {
  readonly id: Prisma.FieldRef<"Hero", 'String'>
  readonly name: Prisma.FieldRef<"Hero", 'String'>
  readonly headline: Prisma.FieldRef<"Hero", 'String'>
  readonly subheadline: Prisma.FieldRef<"Hero", 'String'>
  readonly description: Prisma.FieldRef<"Hero", 'String'>
  readonly profileImage: Prisma.FieldRef<"Hero", 'String'>
  readonly resumeUrl: Prisma.FieldRef<"Hero", 'String'>
  readonly githubUrl: Prisma.FieldRef<"Hero", 'String'>
  readonly linkedinUrl: Prisma.FieldRef<"Hero", 'String'>
  readonly createdAt: Prisma.FieldRef<"Hero", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Hero", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Hero findUnique
 */
export type HeroFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * Filter, which Hero to fetch.
   */
  where: Prisma.HeroWhereUniqueInput
}

/**
 * Hero findUniqueOrThrow
 */
export type HeroFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * Filter, which Hero to fetch.
   */
  where: Prisma.HeroWhereUniqueInput
}

/**
 * Hero findFirst
 */
export type HeroFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * Filter, which Hero to fetch.
   */
  where?: Prisma.HeroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Heroes to fetch.
   */
  orderBy?: Prisma.HeroOrderByWithRelationInput | Prisma.HeroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Heroes.
   */
  cursor?: Prisma.HeroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Heroes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Heroes.
   */
  distinct?: Prisma.HeroScalarFieldEnum | Prisma.HeroScalarFieldEnum[]
}

/**
 * Hero findFirstOrThrow
 */
export type HeroFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * Filter, which Hero to fetch.
   */
  where?: Prisma.HeroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Heroes to fetch.
   */
  orderBy?: Prisma.HeroOrderByWithRelationInput | Prisma.HeroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Heroes.
   */
  cursor?: Prisma.HeroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Heroes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Heroes.
   */
  distinct?: Prisma.HeroScalarFieldEnum | Prisma.HeroScalarFieldEnum[]
}

/**
 * Hero findMany
 */
export type HeroFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * Filter, which Heroes to fetch.
   */
  where?: Prisma.HeroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Heroes to fetch.
   */
  orderBy?: Prisma.HeroOrderByWithRelationInput | Prisma.HeroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Heroes.
   */
  cursor?: Prisma.HeroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Heroes.
   */
  skip?: number
  distinct?: Prisma.HeroScalarFieldEnum | Prisma.HeroScalarFieldEnum[]
}

/**
 * Hero create
 */
export type HeroCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * The data needed to create a Hero.
   */
  data: Prisma.XOR<Prisma.HeroCreateInput, Prisma.HeroUncheckedCreateInput>
}

/**
 * Hero createMany
 */
export type HeroCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Heroes.
   */
  data: Prisma.HeroCreateManyInput | Prisma.HeroCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Hero createManyAndReturn
 */
export type HeroCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * The data used to create many Heroes.
   */
  data: Prisma.HeroCreateManyInput | Prisma.HeroCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Hero update
 */
export type HeroUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * The data needed to update a Hero.
   */
  data: Prisma.XOR<Prisma.HeroUpdateInput, Prisma.HeroUncheckedUpdateInput>
  /**
   * Choose, which Hero to update.
   */
  where: Prisma.HeroWhereUniqueInput
}

/**
 * Hero updateMany
 */
export type HeroUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Heroes.
   */
  data: Prisma.XOR<Prisma.HeroUpdateManyMutationInput, Prisma.HeroUncheckedUpdateManyInput>
  /**
   * Filter which Heroes to update
   */
  where?: Prisma.HeroWhereInput
  /**
   * Limit how many Heroes to update.
   */
  limit?: number
}

/**
 * Hero updateManyAndReturn
 */
export type HeroUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * The data used to update Heroes.
   */
  data: Prisma.XOR<Prisma.HeroUpdateManyMutationInput, Prisma.HeroUncheckedUpdateManyInput>
  /**
   * Filter which Heroes to update
   */
  where?: Prisma.HeroWhereInput
  /**
   * Limit how many Heroes to update.
   */
  limit?: number
}

/**
 * Hero upsert
 */
export type HeroUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * The filter to search for the Hero to update in case it exists.
   */
  where: Prisma.HeroWhereUniqueInput
  /**
   * In case the Hero found by the `where` argument doesn't exist, create a new Hero with this data.
   */
  create: Prisma.XOR<Prisma.HeroCreateInput, Prisma.HeroUncheckedCreateInput>
  /**
   * In case the Hero was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HeroUpdateInput, Prisma.HeroUncheckedUpdateInput>
}

/**
 * Hero delete
 */
export type HeroDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
  /**
   * Filter which Hero to delete.
   */
  where: Prisma.HeroWhereUniqueInput
}

/**
 * Hero deleteMany
 */
export type HeroDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Heroes to delete
   */
  where?: Prisma.HeroWhereInput
  /**
   * Limit how many Heroes to delete.
   */
  limit?: number
}

/**
 * Hero without action
 */
export type HeroDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hero
   */
  select?: Prisma.HeroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hero
   */
  omit?: Prisma.HeroOmit<ExtArgs> | null
}
